services:
  db:
    container_name: db
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./db/data:/docker-entrypoint-initdb.d
    ports:
      - ${POSTGRES_LISTEN_PORT}:5432
    env_file: .env

